spring:
  application:
    name: jewelbid
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_DATABASE:jewelbid}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:postgres}
  security:
    user:
      name: ${SECURITY_USER:admin}
      password: ${SECURITY_PASSWORD:password}
      roles: ADMIN

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    enabled: true
